# Generated by Django 6.0.3 on 2026-03-19 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('instructor', 'Instructor'), ('student', 'Student')], max_length=20),
        ),
    ]
