# Generated by Django 6.0.3 on 2026-03-15 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate',
            old_name='issue_date',
            new_name='issued_date',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='certificate_id',
        ),
        migrations.AddField(
            model_name='certificate',
            name='certificate_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Progress',
        ),
    ]
