# Generated by Django 6.0.3 on 2026-03-19 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_mcqquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='ai_review',
            field=models.TextField(blank=True, null=True),
        ),
    ]
